#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
#after line nine print hi

count = 0;
while [ $count -lt 10 ]
do 
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best Schoo"
	(( count++ ))
done
