#!/usr/bin/env bash
#RSA key pair.

#Requirements:

#Name of the created private key SHOULD  be school
#Number of bits  to be created 4096
#Created key must be protected by the passphrase betty

ssh-keygen -t rsa -b 4096 -N "betty" -f ./school
